### ISSUE TITLE
linux

### ISSUE THREAD

**Issue by k3ldon** [aura-project/melia#104]
Hi I have seen a lot of activity again in the project but i have some questions:

how i can compile in linux?
What are the specifications of the server?

Ty

**Comment by celophi** [comment]
You should be able to compile with Mono 4.5+ I believe. We use Travis CI to compile which does so on an Ubuntu distribution using that library. If you'd like you can see so [here](https://travis-ci.org/aura-project/melia/builds/272167989?utm_source=github_status&utm_medium=notification) as an example.

**Comment by exectails** [comment]
As celophi said, you need Mono (v3 or above atm). After you've installed it (this process varies between distributions), you just run `xbuild /p:Configuration=Release Melia.sln` in your Melia folder, and afterwards you can start the separate servers from the bin/Release/ folder with Mono, eg: `mono LoginServer.exe`.

Please keep in mind that Melia is still very early in development though, and we have just started getting it back up to speed with the latest client. It's not really playable right now.

Nothing can be said regarding specifications yet, because nobody has ran any benchmarks yet.

**Comment by k3ldon** [comment]
thanks for replying, I already compiled it with mono 4.3. I understand the emulator is very beta stage yet... but still work how is the proyect and to make some contributions

**Comment by exectails** [comment]
Good to hear that you got it, I'll close this then =)
