### ISSUE TITLE
events config idea

### ISSUE THREAD

**Issue by highattack30** [aura-project/melia#33]
maybe there will be in config events stuff look like

[EVENTS]
//this will apply holiday decorations
xmass = 1
halloween = 1

and such on for holiday
0 = off 1= on

**Comment by Cosrnos** [comment]
I'm gonna close this issue since it doesn't seem to have a lot of substance. While it's great to try and think how this config will work, it would be more beneficial to talk about implementation. I'm not trying to discourage anything but how a config variable will work doesn't necessarily belong in github with the code base. The discussions here should be fairly technical in nature.

I will encourage you to have these discussions in the gitter channel for this project or on the [Project Aura  - Melia General Forums](http://aura-project.org/forum/forum/67-general/)
