### ISSUE TITLE
"G" in chat tries to bring up a guild

### ISSUE THREAD

**Issue by dr4luc0n** [aura-project/melia#45]
Trying to type /go and it deletes my words when I press g and says I don't have a guild, which I dont

**Comment by exectails** [comment]
This is expected behavior, as a slash `/` is the default prefix for the official commands. While Melia does support commands prefixed with a slash, our default prefix is greater-than `>`. You can change the prefix in the [commands.conf](https://github.com/aura-project/melia/blob/master/system/conf/commands.conf#L5).
