### ISSUE TITLE
Team name not loading if you delete a character

### ISSUE THREAD

**Issue by huenato** [aura-project/melia#67]
Once you delete a character, team name does not load

https://www.youtube.com/watch?v=-Qr7tvAuPbM

**Comment by exectails** [comment]
Huh, weird o.o The delete function was written long before we had access to logs though, so maybe we're just missing something little. We'll have to look into that. If someone wants to save us some work, feel free to post a packet log of a character getting deleted.

**Comment by exectails** [comment]
I've test this just now, but I can't reproduce it. Does this happen every time for you?

**Comment by huenato** [comment]
Yup.
It seems to be happening on a second character.
If I have only one there is no problem it seems.

**Comment by exectails** [comment]
I wouldn't say that, a bug is bug, we just have to figure out what's causing it.

**Comment by huenato** [comment]
Team name was missing on CreateCharacter() in LoginDb.cs
http://puu.sh/oIn2h/ebcfa8e5e2.png

**Comment by exectails** [comment]
I knew it was missing, but that shouldn't have been a problem o,o Unless the character was loaded before the save was through... hm. Yea, that team name thing actually has to be reevaluated, I don't remember why we even put the team name field on the character table. That's why I didn't fix this yet. But if it fixes this issue, we should do it for now.

**Comment by Dr4kk0** [comment]
If i'm not wrong you put the team name in character table because at the time was not possible to create new characters due to this field is missing.

**Comment by exectails** [comment]
@Dr4kk0 No, that was something else.
