### ISSUE TITLE
Game Database Migration

### ISSUE THREAD

**Issue by sant0ro** [aura-project/melia#76]
Hi @exectails i saw your Game Package Database (Item Identification, NPC's, and etc) are statically stored in a `TXT` Database. In terms of performance and data integrity that's not good. Recommend you to store it in a real SQL Database. Here are some tips (in my opinion):
1. Internal Game Data, like NPC's, are loaded one-time in the Emulator start up, directly from Database. Following the Software Design Patterns you will have Storage's and Factories. The Data is stored in the memory by a cache. And the Administrators can change it by a Database Explorer, like phpMyAdmin or Navicat, and use commands like `:npc_update` to Update NPC's details. Using in TXT is really easy to someone break the Data segments or corrupt it. Also is heavy to edit.
2. File Buffers, reading the whole content of a TXT file will spent more time than SQL Queries.
3. Is more easily to edit in a Relational Database. But those type of data doesn't actually need have any relation, only if exists direct linkage between (as example) NPC <-> Item.

**Comment by exectails** [comment]
Thanks for your suggestion. This was briefly discussed in #11, but I'll try to get over how we came to use text data in Aura and now in Melia.

Me coming from eAthena we initially used CSV in Aura, because it was quick and simple to do and faster than JSON. My CSV parser was also faster than a simple get everything query in MySQL, which was important because a few users were already complaining about the load time.

The plan was to maybe some day add SQL optionally, just like eAthena, for people who wanted it. Personally I've always used text databases, because I found them easiest to work with in my use cases.

We then reached a point where CSV became unwieldy, because we wanted to use nested data, arrays, and objects, basically something like JSON, to structure the data better and have less databases. For example, instead of a skill and a skill rank db (each skill had X ranks and each skill rank had specific properties), skills could be cleanly put into one database. You would have everything in one place and could asses it at a glance. Same for monster's equip, skills, and drops.

This time I managed to load JSON almost as quickly as CSV, and with some caching the loading time was on-par, so we had the structure and performance we wanted now.

With this setup I implemented a new system during a major rewrite of Aura, the [User Folder System](https://github.com/aura-project/melia/wiki/User-folder), where files from the user folder can overwrite and extend files in the system folder. Basically, it works similar to the import folder in eAthena, but on more than just configuration.

For data overloading you have an item_db2 in eAthena, but that is quite limiting, as it's only one db. To do this properly you would need a copy of *every* db, which doesn't seem like good design.

This lead us to the JSON text dbs we have now, and while Melia doesn't necessarily need structured data (at least *yet*), I'd hate to lose the User Folder System, because in my opinion it's vastly superior to any kind of customization solution we could come up with for an actual database.

I have a hard time thinking of things that SQL would do better. In fact, I can think of a few more things that text does better in my opinion, like updating. Though this is coming from someone who generally prefers text.

To me, the question is what can SQL offer us that text data can't, that is worth sacrificing the pros that come with text? To go over your points:

>Internal Game Data, like NPC's, are loaded one-time in the Emulator start up

Right now NPCs are completely controlled by the scripts themselves, which gives complete control over them to the scripter and makes sharing and adding them easier.

>File Buffers, reading the whole content of a TXT file will spent more time than SQL Queries.

Actually, as mentioned above, in early tests my CSV parser was faster than an uncached SQL query, and with caching the databases there should be no noticable difference. Honestly, I'd be worried about it becoming slower if you add the overhead of ORMs (#77).

>Is more easily to edit in a Relational Database.

I'd say this is subjective, and the reason eAthena supported both. Depending on the format of the text data, what you're trying to change, and your setup, editing text data can be easier and faster, as it was for me in the past. It's largely a matter of preference I think.

**Comment by alyyasser** [comment]
i guess, if you'd prefer JSON right now, then NoSQL could be usefull

**Comment by exectails** [comment]
@alyyasser How so?

**Comment by alyyasser** [comment]
most of NoSQL db using JSON-like structure, i.e. MongoDB. but, i think it's preference matter. for me, i'd like to use dbms rather than text/file data, but SQL is 'pain in the ass' for me, so i prefer using NoSQL and some libraries.

**Comment by exectails** [comment]
Sorry, I'm actually not all that familiar with specific NoSQL database implementations. Are you saying those you've mentioned store the data in JSON files, so you'd essentially get both, access via files *and* libraries/tools?

**Comment by sant0ro** [comment]
Exactly @exectails... CouchDB stores purely jSON files. And you can display all result obviously in jSON. The funniest thing of CouchDB it's that you iterate through SQL in the Database.

Give a better look here: http://couchdb.apache.org/

**Comment by exectails** [comment]
Well, the premise of having both is certainly interesting.

**Comment by exectails** [comment]
My main concerns for not loading data the way we do now anymore are performance and support for the user folder system, which are both important and useful to have in my opinion. If another solution doesn't at least offer the same features+more or does anything else to outweigh losing them, I don't see a logical reason to spend valuable time on learning and switching to a new system.

**Comment by exectails** [comment]
I will close this for now, since the people who were advocating for it don't seem to be around anymore, and because other data management methods don't fit our current needs well.
