### ISSUE TITLE
Usage of NHibernate and FluentNHibernate

### ISSUE THREAD

**Issue by sant0ro** [aura-project/melia#77]
Hi @exectails i don't know if you already know about Hibernate, but here goes the reference: [wikipedia.org/wiki/Hibernate](wikipedia.org/wiki/Hibernate) Actually exists a port of Hibernate to C#, called NHibernate... [https://github.com/nhibernate](https://github.com/nhibernate)

This will be awesome since,
1. NHibernate does the Data Modeling based in MVC Models
2. Static Queries aren't anymore needed, just use Hibernate
3. And all other features of Hibernate

**Comment by exectails** [comment]
This was briefly discussed in #11, where I agreed that we should consider it. We didn't have anyone with any experience using such libraries though. Personally I prefer raw queries, but I can certainly see why ORM appeals to the majority of people.

**Comment by karocksjoelee** [comment]
Hey ~ just wonder if this still in development ?

**Comment by Hirasu** [comment]
@karocksjoelee 
Yes: https://github.com/Ci3l0phi/melia/commits/i157375

**Comment by exectails** [comment]
I'm going to close this for now, since the ones advocating for it aren't around anymore, and I would rather focus on the actual emulator than rewriting the database code and learning a new framework.

I'm open to the suggestion, but in my opinion, for any bigger change in an application there should be a payoff that balances out the costs of the change. ORMs can be really useful in some cases, but you shouldn't downplay the advantages of SQL.

To me, one of those advantages is that SQL is, or at least should be, known to most programmers who ever did anything database related. That means that anybody can hop into the code and make changes. An ORM, like any framework, requires learning how to work with it, while simultaneously unlearning how you're used to do things.

While someone who's using ORMs daily might be bothered by writing database code manually, they're most likely still able to do it, while <insert ORM> potentially requires initial learning from every contributor who has to make any changes to the database.
