### ISSUE TITLE
Stuck in character creation, keeps saying "name already exists"

### ISSUE THREAD

**Issue by bibiano** [aura-project/melia#80]
Hey man - 

Really appreciate all the work you've done here. 

I understand there are incompatibility issues with the current state of melia and iTOS' latest version, but I still went and gave the setup a chance. 

I was able to get as far as the character creation screen. Unfortunately, I'm stuck and keep getting a "name already exists" prompt. Here's a screenshot: http://i.imgur.com/xrVq81o.jpg

<img src="http://i.imgur.com/xrVq81o.jpg" />

I'm not very familiar with databases but I had a wild guess this might have to do with checking and updating the database. 

This is what the login window command line is outputting: http://i.imgur.com/gEVO4Jz.png

<img src="http://i.imgur.com/gEVO4Jz.png" />

Is there a way I can manually change the value/property/attribute (I don't know the right word :D) of that "entry"? I think I can macguyver my way around using HeidiSQL if possible. 

Thanks for your time, and hope to hear from you soon!

**Comment by exectails** [comment]
The database is most likely working fine, the problem lies somewhere in the packets. My guess is that the character does exist, that you did create it (this you could check in the database), but that it's not displayed, because the response packets are incorrect. The server tells the client about the character, but the client doesn't understand the information, because it's not compatible.

Without updating the packets you won't be able to get past this I'm afraid =/

**Comment by bibiano** [comment]
Thanks man! Guess I'll just keep my eye on any updates from you. :)

If you need someone to help with bug reporting, I'm willing to assist. 

By the way, I forgot to include - I also got the following error & warning when I tried to run main.sql in HeideSQL: 

<img src="http://i.imgur.com/O4CrcZH.png" />

<img src="http://i.imgur.com/Lu2rm49.png" />

Not sure if that somehow contributed to the issue. 

Thanks again!

**Comment by exectails** [comment]
Looks like you tried to run it twice.

**Comment by bibiano** [comment]
Ack! Explains it. Haha thanks man!
