### ISSUE TITLE
Talking too fast to NPC crashes Channel Server

### ISSUE THREAD

**Issue by huenato** [aura-project/melia#9]
How to reproduce:
Keep pressing enter and selecting it's option or spam the Esc button while talking to it.

**Comment by exectails** [comment]
I can't reproduce the enter problem, but the Esc one. It seems like we're not handling `CZ_DIALOG_ACK` properly. Though it doesn't crash the server, but the characters kinda gets stuck in the conversation. Is that what you meant?

Problem: If you press Escape while you're in a select, the packet sent is not `CZ_DIALOG_SELECT`, but `CZ_DIALOG_ACK`, with the unknown int being 0. Normally that int seems to be 1. When hitting escape on a normal dialog message the int is -1 instead of 1.

I assume that packet with the int being anything but 1 means cancel the dialog, instead we try to resume the script right now, which doesn't  work out for some reason... maybe Lua silently fails because it's waiting for a return value for the select call?

**Comment by huenato** [comment]
Or is it trying to resume something that's not there anymore?

**Comment by exectails** [comment]
That *should* result in an error, but not in a crash (if it is crashing). Do you get any errors? You can check the log files in the log folder if the channel window actually closes.

**Comment by huenato** [comment]
No errors here in the logs :/

**Comment by exectails** [comment]
You haven't answered my question yet, does the channel server actually *crash*? As in the window just closes?

**Comment by huenato** [comment]
It just closes.

**Comment by huenato** [comment]
I recorded a video and I got the error.
PANIC: unprotected error in call to Lua API (attempt to call a thread value)

It was so fast that I didn't see it D:
http://gfycat.com/BountifulClumsyHoneycreeper

**Comment by exectails** [comment]
So the error comes from Lua, that explains how it can just crash o~o

I get literally 10 results for that error on Google, and most of those are useless. I think what it means is that Melia is trying to call something that is not a function. Since we're spamming ACK packages, which in turn spam calls to Resume, I assume that on the second or third call the Lua stack has changed.

We have to make sure this doesn't happen, Lua isn't thread-safe. Maybe by locking the ScriptState, that way we can't enter Resume twice anymore. We also have to test if the dialog should close completely when you press Esc, which I assume.

**Comment by exectails** [comment]
Okay, it's not a race condition. It's much simpler than that, we're allowing a resume on a finished script. Silly me.

**Comment by exectails** [comment]
To further secure this, we should probably add a check in the script manager for whether the script/function is finished... gotta research how to do that with Lua.
